name: Deploy to Nekoweb
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare files
        run: |
          mkdir -p ./deploy
          rsync -av --exclude='.git' --exclude='.github' --exclude='deploy' --exclude='deploy2nekoweb' ./ ./deploy/
      - name: Debug
        run: ls -la ./build/
      - name: Deploy to Nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'scribe-unmoored.nekoweb.org'
          nekoweb-username: 'scribe-unmoored'
          directory: './deploy'
