name: Deploy to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: |
          zip -r site.zip . \
            -x ".git/*" \
            -x ".github/*"

      - name: Upload to Nekoweb
        run: |
          curl \
            -H "Authorization: ${{ secrets.NEKOWEB_API_KEY }}" \
            -F "file=@site.zip" \
            https://nekoweb.org/api/upload
