name: Deploy to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare build
        run: |
          mkdir build
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='build' \
            ./ ./build/

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@0.2.1
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: './build'
          DEPLOY_DIR: '/'
          DELAY: '0.5'
          NEKOWEB_PAGENAME: 'scribe-unmoored'
          ENCRYPTION_KEY: ${{ secrets.NEKOWEB_ENCRYPTION_KEY }}
